- pom.xml
This PR adds source plugin to the build process of the mvn.
> [MO] - adds maven source plugin to build

- .azure/build-pipeline.yaml
This PR adds support for build pipeline to be able to trigger tags.  
> [MO] - add tags trigger

- README.md
- src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
- src/main/java/io/strimzi/test/container/StrimziZookeeperContainer.java
- src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java
I've not thought of this the first time. I think it is easier than the system property alternative.
> Accept custom image as constructor parameter

- src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
- src/main/java/io/strimzi/test/container/StrimziZookeeperContainer.java
- src/main/resources/kafka_versions.json
- src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java
This PR is adding a new Kafka version (3.1.0) + solving problems with starting KRaft in `3.1.0`.
> [MO] -> adding Kafka 3.1.0 + solve problem with starting KRaft in 3.1.0

- pom.xml
This PR change version of this repo to future one.
> [MO] - bump-up project version

- src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
Extract the start command in its own method to allow consumers to override it if needed.
Also, fix the file test as the file must be executable (and not only existing).
Context: We are seeing a few "text file busy" when starting strimzi. It's related to a race condition on the file system as the file exists, but the executable flag is not set or not completely set. This PR waits for the file to be executable and allows overriding the command to let us find the best approach (if -x is not enough).
> Fix starter script test

- src/main/resources/kafka_versions.json
This PR adds new Kafka images (i.e., 3.1.1 and 3.2.0). 
> [MO] - adding kafka 3.1.1, 3.2.0

- src/main/resources/kafka_versions.json
This PR adds a new Kafka version 3.2.1 to the JSON file (where all supported Kafka versions are).
> [MO] - adding Kafka 3.2.1 to json

- pom.xml
- src/test/java/io/strimzi/test/container/StrimziKafkaContainerTest.java
This PR updates our current dependencies versions.
> [MO] - bump up new versions of dependencies

- pom.xml
This PR adds a new version of test container.
Signed-off-by: morsak <maros.orsak159@gmail.com>
> [MO] - bump new version of test container

- src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
- src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java
- src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java
Signed-off-by: Tom Bentley <tbentley@redhat.com>
> Add getClusterId() for KRaft containers

- .azure/build-pipeline.yaml
- .azure/templates/steps/setup_java.yaml
- pom.xml
This PR updates the ubuntu old image to the latest because of:
```
##[error]The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04 or ubuntu-22.04 (ubuntu-latest). For more details, see https://github.com/actions/runner-images/issues/6002
,##[error]The remote provider was unable to process the request.
```
> Update Azure CI to latest vmImage

- pom.xml
This PR updates a version for the main branch.
> Bump main to 104 snapshot

- pom.xml
This PR adds a 0.105.0-SNAPSHOT version to the main branch.
> Bump version to 0.105.0-SNAPSHOT

- pom.xml
This PR updates a new version in `pom.xml`.
> Bump new 106 version

- src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
- src/main/resources/kafka_versions.json
This PR updates a Kafka minor version.
> Update Kafka minor version

- pom.xml
This PR bumps the new version to the main branch.
> Bump up version of project to 0.107.0

- src/main/resources/kafka_versions.json
This PR updates 3.6.x Kafka minor version.
> Update to Kafka 3.6.2

- pom.xml
This PR bumps a few project dependencies to use the latest releases.
> Bump up versions to the latest one

- pom.xml
This PR updates pom.xml to 0.108.0-SNAPSHOT version.
> Bump up pom.xml to 0.108.0-SNAPSHOT

- pom.xml
This PR updates a few dependencies
> Bump up a few dependecies

- pom.xml
This PR updates the checkstyle version, mirrors the operator repo, and fixes the `gpg` version.
> Update checkstyle version and fix gpg version

- pom.xml
This PR updates the `pom.xml` version after we recently released the 0.108.0 test container.
> Update pom version after release

- src/main/resources/kafka_versions.json
This PR adds a new Kafka 3.8.1.
> Add support for Kafka 3.8.1 

- pom.xml
This PR adds code dependency for Kafka 3.8.1
> Bump Kafka 3.8.1 depedency

- README.md
This PR documents how one can solve problems by using Podman. More can be found [1]. 
[1] - https://github.com/strimzi/test-container/issues/102
> Timeout issue using Podman

- README.md
- src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
- src/main/resources/kafka_versions.json
- src/test/java/io/strimzi/test/container/StrimziKafkaClusterIT.java
- src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java
- src/test/java/io/strimzi/test/container/StrimziKafkaContainerMockTest.java
- src/test/java/io/strimzi/test/container/StrimziKafkaKRaftClusterIT.java
- src/test/java/io/strimzi/test/container/StrimziKafkaKRaftOauthIT.java
This PR adds Kafka 3.9.0 version to our matrix.
> Add Kafka 3.9.0

- src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
- src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
- src/main/java/io/strimzi/test/container/StrimziZookeeperContainer.java
- src/main/java/io/strimzi/test/container/WaitException.java
This fixes a bunch of broken javadoc tags.
> Fix javadoc issues

- pom.xml
- src/main/java/io/strimzi/test/container/StrimziConnectCluster.java
- src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
- src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
- src/main/java/io/strimzi/test/container/StrimziZookeeperContainer.java
- src/test/java/io/strimzi/test/container/StrimziConnectClusterTest.java
- src/test/java/io/strimzi/test/container/StrimziKafkaClusterTest.java
This PR adds a few updates to our test cases to increase coverage (both mutation and line). Moreover, it also refactor magic strings (i.e., zookeeper) and encapsulate it to specific variable.
> Improve coverage a bit

- pom.xml
This PR updates a few dependencies.
> chore: update dependencies in pom.xml

- src/main/resources/kafka_versions.json
This PR adds the recently released Kafka 3.9.1.
> Add Kafka 3.9.1
