strimzi/test-container

pom.xml
src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/test/java/io/strimzi/test/container/AbstractIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java
src/test/java/io/strimzi/test/container/StrimziZookeeperContainerIT.java

This PR adds ParametrizedTests for our test cases. Currently, we have been running only tests for the latest version. Now we would be able to catch errors on different supported Kafka versions. 

[MO] - adds ParametrizedTest for test cases

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/main/java/io/strimzi/test/container/UnsupportedKraftKafkaVersionException.java
src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java

This PR restrict usage of KRaft for Kafka `2.8.1` and it's allowed only for `3.x.x` Kafka versions. Moreover, I have added tests cases for sanity checks. 

[MO] - restrict KRaft for Kafka 2.8.1

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java

When container host IP is not on localhost kraft containers fail on startup.

Controller listens on the localhost instead of container host

---

src/main/java/io/strimzi/test/container/StrimziZookeeperContainer.java

This PR adding a method to the `StrimziZookeeperContainer`, which provides a string representation of `host:port` to be able to connect to the running ZooKeeper instance.

[MO] - `StrimziZookeeperContainer` -> connnect string method

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java

When Base64 formatted randomly generated uuid starts with '-', the format storage command fails.

Wrap cluster uuid around quotes

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/main/java/io/strimzi/test/container/StrimziZookeeperContainer.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java

Otherwise, the configuration for custom container network is overridden by the doStart method.
Signed-off-by: Ozan Gunalp <ozangunalp@gmail.com>

Avoid setting container config on doStart method

---

pom.xml
src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java

The `kafka-clients` 3+ dependency is currently declared with `compile` scope, which makes the library harder to integrate in code bases when using a `kafka-clients` 2+ (code base where the migration to `kafka-client`` 3+ is not easily doable).
The dependency is only used to generate an UUID in the `StrimziKafkaContainer` class using the Kafka client's `org.apache.kafka.common.Uuid`, in order to apply a specific filter to ignore 2 specific Kafka UUIDs (metadata topic uuid & zero uuid) and to encode the UUID in base64.
The constraints to have a `compile` dependency on the `kafka-clients` seems very high compared to the benefits.

Remove compile dependency on kafka-clients

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerTest.java

I found (while trying to configure a `ssl.keystore.password` that happened to contain spaces) that there was not quoting of the map values passed to `StrimziKafkaContainer.withKafkaConfigurationMap`: They were open to interpretation by the shell. This PR quotes them using single quotes.

Shell quoting for Kafka config

---

pom.xml
src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/test/java/io/strimzi/test/container/StrimziZookeeperContainerIT.java

* Update docker java version, since it's a transitive dep of testcontainers
* `getContainerIpAddress()` got deprecated, so use `getHost`()
* `systemUnderTest` can be null if the instantiation failed, so add a null check to avoid hiding the original exception.

Fix #40: Update test containers version

---

src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterTest.java

This PR fixes the problem when one will hypothetically want to create a Kafka cluster with zero nodes. Currently, it won't fail, therefore I modified the condition to do so. Plus I have added a few unit tests to check that behaviour.

[MO] - Kafka cluster number of brokers fixed + unit tests

---

pom.xml

This PR updates Jackson to 2.13.4 / 2.13.4.1 to address thelatest CVEs.

Update Jackson to address CVEs

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/main/resources/kafka_versions.json
src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java

This PR adds support for Kafka versions, which were introduced (https://github.com/strimzi/test-container-images/pull/14). Also, it adds some minor changes (i.e., changing regex for waiting until the cluster is ready).

Update to the newest Kafka + some minor changes

---

src/main/resources/kafka_versions.json
src/test/java/io/strimzi/test/container/AbstractIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java

This PR adds recently released Kafka versions. Also, it updates a few test cases where we need to check different logs because of change.

Add Kafka 3.4.1 and 3.5.0 + fix tests

---

.azure/build-pipeline.yaml
.azure/templates/steps/push_artifacts.yaml
pom.xml

The older sonatype maven plugin (`1.6.3`) is failing when pushing artefacts using Java 17. This update should solve such a problem with the latest version `1.6.13`.
Basically a mirror of the https://github.com/strimzi/strimzi-kafka-operator/pull/7946. 
Plus I have added for flaky test cases (that it well try at least 3 times if they end up failing) 
Plus, publishing artefacts will done only in scope of Java 17 build

Make maven sonatype plugin work also with Java 17, and publish for 17 only

---

.checkstyle/checkstyle.xml
src/main/resources/kafka_versions.json
src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java

This PR adds Kafka 3.5.1 and recently released Kafka 3.6.0 to our JSON file + one test case covering a functionality of Kafka container

Add a new versions of Kafka 3.6.0 and 3.5.1

---

src/main/resources/kafka_versions.json

This PR adds the latest Kafka version (3.7.0)

Add a 3.7.0 Kafka version

---

.azure/scripts/push_to_nexus.sh
pom.xml

- Bugfix
Some changes at Sonatype broker the way we push the JAR artifacts to Sonatype Nexus. This PR fixes it by updating the Sonatype plugin. It also updates the script we use for it to make it fail in case of problems.
It also adds Lukas to the maintainer list where he was missing.

Fix pushing of artifacts to Nexus

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/main/resources/kafka_versions.json

This PR adds a Kafka 3.7.1 version.
Update:
So there is one needed change for 3.7.1 and higher versions.
```java
//  from: Recorded new controller, from now on will use node 
//  to  : Recorded new ZK controller, from now on will use
```
So I have updated the waiting message to match both of these logs :)

Add Kafka 3.7.1 version

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java

This PR solves [1] issue. TLDR; when we generate UUID starting with `-.....` the command treats it as a new parameter and therefore fails. 
[1] - https://github.com/strimzi/test-container/issues/72

Fix KRaft storage formating with UUID starting with dash

---

src/main/resources/kafka_versions.json

This PR adds recently released Kafka 3.8.0 to our test container.

Add Kafka 3.8.0 to test containers

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/main/java/io/strimzi/test/container/StrimziZookeeperContainer.java
src/main/java/io/strimzi/test/container/Utils.java

I've been playing around with this library to investigate listener configurations (likely helpful to #63), but I am unable to run the tests in an environment with podman. It turns out that copying a `MountableFile` to the containers preserves the user and group Ids from the host machine via an intermediate tar file. This fails with podman due to the chown command not being allowed.
The change proposed here is to read the contents of the `MountableFile` prior to copying into the container. This drops the user and group information, which should not be relevant. 
An additional change is to delay copying the Kafka properties until the container is starting, which allows for `withKraft` and `withServerProperties` to be called in any order.

Transfer only contents of Kafka and ZooKeeper properties files

---

pom.xml

In the previous dependency bump of versions, I accidentally typed the wrong version of the nexus dependency (i.e., it should be 1.7.0 instead of 1.7.1). 
This PR should fix the main branch during pushing.

Fix pushing arctifacts because of not resolved version

---

src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/test/java/io/strimzi/test/container/AbstractIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterTest.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java
src/test/java/io/strimzi/test/container/StrimziZookeeperContainerIT.java

This PR tries to address https://github.com/strimzi/test-container/issues/83 by adding a `boolean sharedNetwork`. With such change a user is able to run Kafka cluster with shared network if needed.

Add ability to enable shared network in `StrimziKafkaCluster`

---

src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterTest.java

This PR adds flexibility to `StrimziKafkaCluster` by adapting the Builder pattern. With such change we will easily extend such class adding more parameters. Solves #84.

`StrimziKafkaCluster` builder

---

src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java

This PR fixes a problem, which arises during refactor [1]. In `Deprecated` approach I forgot to update `this.internalTopicReplicationFactor = internalTopicReplicationFactor; and also `validateInternalTopicReplicationFactor` was in-correct resulting in throwing Exception.
[1] - https://github.com/strimzi/test-container/pull/86

Fix internal topic handling in constructors

---

src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterTest.java

This PR allows specifying the Kafka version in `StrimziKafkaCluster`. Moreover, I have added a few UTs to cover such changes with some aux methods only dedicated to tests. Additionally, I have only made such a change for `Builder` to allow users to specify such a version (for those users, who are using old constructors we still use the default/latest version).

Add possiblity to specify Kafka version in `StrimziKafkaCluster`

---

.checkstyle/checkstyle.xml
src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/test/java/io/strimzi/test/container/StrimziKafkaKRaftClusterIT.java

This PR adds support for KRaft within `StrimziKafkaCluster`. Currently, we are able to run in KRaft mode with the single-node instance.

`StrimziKafkaCluster` KRaft mode

---

README.md
src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/test/java/io/strimzi/test/container/StrimziKafkaKRaftClusterIT.java

This PR updates a README.md with recent changes and covers everything with KRaft Kafka cluster-related stuff. Moreover, it fixes a few typos inside README.md

README.md update

---

src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java

This PR handles exceptions correctly by throwing them instead of just calling printStackTrace(). Also, now it throws a more informative error message than before, as stated in issue #80.

Fix start() in StrimziKafkaCluster to propagate exception correctly

---

src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java

This PR removes constructors from the `StrimziKafkaCluster` class. Now users should only use StrimziKafkaClusterBuilder during object creation.

Remove constructors from StrimziKafkaCluster

---

src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java

In the Add proxy container configuration (#44), we forgot to add stop(). That causes containers to run during all other test cases. Only recently (with more Kafka versions) it showed that we are out of memory in Azure CI:
```java
##[warning]Free memory is lower than 5%; Currently used: 95.10%
##[warning]Free memory is lower than 5%; Currently used: 95.10%
```
This should fix the problem above.
Note: 
I think we should double-check before each test that none containers are running to avoid this in the future.

Fix memory problems inside test suite

---

.azure/build-pipeline.yaml
README.md
pom.xml
src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/main/java/io/strimzi/test/container/StrimziZookeeperContainer.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterTest.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerTest.java
src/test/java/io/strimzi/test/container/StrimziKafkaKRaftOauthIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java

This PR adds to the test container mutation testing. Specifically [1]. During adoption, I saw that there are a lot of paths in the `Strimzi*` classes, which are not tested. So I have also added a few tests to solve it. 
You can read about the benefits of mutation testing here [2].
Moreover, I have updated Azure-CI with mutation testing within the pipeline. Also if someone writes a new code then the build may fail because I have set the following thresholds. So there will be a need to add UTs to cover such features and be at least on such threshold as we have currently.
```
<mutationThreshold>80</mutationThreshold>
<coverageThreshold>71</coverageThreshold>
```
[1] - https://pitest.org/
[2] - https://www.arcmutate.com/benefits/

Mutation testing 

---

.azure/build-pipeline.yaml
pom.xml
src/test/java/io/strimzi/test/container/AbstractIT.java

This PR adds a surefire plugin to run UTs within the test container.

Add Surefire plugin

---

pom.xml
src/main/java/io/strimzi/test/container/KafkaVersionService.java
src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/test/java/io/strimzi/test/container/KafkaVersionServiceTest.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerMockTest.java

This PR adds the `CONTROLLER` to `advertised.listeners`.

Add Controller listener to the advertised.listeners

---

src/main/java/io/strimzi/test/container/AuthenticationType.java
src/main/java/io/strimzi/test/container/KafkaVersionService.java
src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/main/java/io/strimzi/test/container/Utils.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerMockTest.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerTest.java
src/test/java/io/strimzi/test/container/StrimziKafkaKRaftClusterIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java

- Removed usage of deprecated APIs
- Minor refactorings and code simplifications

Various Java cleanups

---

pom.xml

After release of strimzi-test-container 0.109.0 is done, we should update pom.xml to newer version.

Bump main to 0.110.0-SNAPSHOT

---

pom.xml

As https://github.com/hcoles/pitest/releases/tag/1.17.2 is released with the fix [1] of excluding lambdas (and nested lambdas). We can increase the mutation coverage of our test suite.
[1] - https://github.com/hcoles/pitest/pull/1362

Update pitest and increase mutation coverage

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerMockTest.java

This PR addresses an intermittent issue where Kafka brokers fail to form a quorum due to mismatched voter keys in the Raft consensus algorithm. The problem occurs approximately 1 out of every 5 test runs (which I tried)...
Brokers occasionally fail to form a quorum, with logs showing repeated messages like:
```java
Leader sent a voter key... that doesn't match the local key...; returning INVALID_VOTER_KEY
```
The advertised listeners for the CONTROLLER listener are set to localhost (using `getHost()` method), while controller.quorum. voters specify hostnames like broker-0, broker-1, etc. This mismatch leads to brokers advertising their controller endpoints incorrectly, causing other brokers to attempt connections to localhost instead of the correct broker addresses.
Using localhost for …

Fix Intermittent Kafka Quorum Formation Issue

---

pom.xml
src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerTest.java
src/test/java/io/strimzi/test/container/StrimziKafkaKraftContainerIT.java

Fixes https://github.com/strimzi/test-container/issues/124

Check node and broker id equality in KRaft mode on start up and not in broker.id setter

---

pom.xml

This PR updates a few dependency versions.

Bump a few dependency versions 

---

src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java

Minor change to remove the now unused `useKraft` field and comments that reference it.

Remove unused useKraft field and associated comments

---

src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterTest.java

This PR renames brokers to nodes to reflect KRaft’s mixed roles and exposes GenericContainer instances via getNodes(), enabling direct access to container-level operations like port exposure and file mounting. Moreover, it deprecates our getBrokers() method and directly tells the end user to use getNodes().

Expose GenericContainer from StrimziKafkaCluster via getNodes() method

---

.azure/scripts/push_to_nexus.sh
.azure/scripts/settings.xml
.azure/templates/steps/push_artifacts.yaml
pom.xml

This PR addresses part of https://github.com/strimzi/test-container/issues/140, specifically the migration of artefact pushes from the OSSRH legacy system to the new Sonatype Central Publisher Portal.

Moved to use the Sonatype Central Portal

---

.azure/templates/steps/push_artifacts.yaml

This PR fixes an issue about credentials for pushing artifacts to the new Central Portal.

Fixed credentials handling to push to Sonatype Central Portal

---

src/main/java/io/strimzi/test/container/StrimziConnectCluster.java

The `GET /health` endpoint was added to the Connect REST API in Kafka 3.9.0 ([KIP-1017](https://cwiki.apache.org/confluence/display/KAFKA/KIP-1017%3A+Health+check+endpoint+for+Kafka+Connect)) to determine if a Connect worker is healthy.
Since we now only support versions >= 3.9, switch to this endpoint instead of `GET /` for readiness.

Use GET /health endpoint for Connect readiness

---

README.md
src/main/java/io/strimzi/test/container/StrimziKafkaCluster.java
src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaClusterTest.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerIT.java
src/test/java/io/strimzi/test/container/StrimziKafkaContainerTest.java

This PR solves [1]. Currently, we can modify stdout logs altogether. However, in some cases, it's better to store logs for each container in a separate file.
[1] - https://github.com/strimzi/test-container/issues/119

Add support for log collection
